// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://sqmnxftsuvdtawmivifs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxbW54ZnRzdXZkdGF3bWl2aWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk1NDM5MzksImV4cCI6MjA3NTExOTkzOX0.uY2mYV1cTqaTvsOqqPACZCJLeR93wgWylBtPMUKUcxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);